FORMAT: 1A
HOST: https://private-a699a9-lanedb85.apiary-mock.com
# db-lane

New collections as the api evolves



## Users Collection [/users]

### List All Users [GET]

+ Response 200 (application/json)

        [
                {
                    "name": "blane245",
                    "email": "blane@lanedb.com",
                    "isAdministrator": "yes"
                },
                {
                    "name": "rlane",
                    "email": "rlane@lanedb.com",
                    "isAdministrator": "yes",
                },
                    "name": "mlane",
                    "email": "mlane@lanedb.com",
                    "isAdministrator": "no",
                {
                    "name": "elane",
                    "email": "elane@lanedb.com",
                    "isAdministrator": "no",
                }
        ]

### Create a New User [POST]

A user with administrative privledges may add new users

+ Request (application/json)

    + Body
    
            {
                "name": "User's Name",
                "email": "User's email address",
                "isAdministrator": "is the new user an administrator?",
                "choices": 
                    [
                        "yes",
                        "no"
                    ]
            }

+ Response 201 (application/json)

    + Headers

            Location: /users/${id}

    + Body

            {
                "message": `User ${name} with email ${email} added. Administrative privileges: ${isAdministrator]`
            }
            
+ Response 403 (application/json)

    + Headers

            Location: /users

    + Body
    
            {
                "message": "You do not administrative privileges on this api"
            }
            
### Modify a user [PUT]
+ Request (application/json)

    + Body
    
            {
                "name": "User's name",
                "email": "User's email address",
                "isAdministrator": "is the new user an administrator?",
                "choices": 
                    [
                        "yes",
                        "no"
                    ]
            }

+ Response 201 (application/json)

    + Headers

            Location: /users/${id}

    + Body

            {
                "message": `User ${name} with email ${email} had been modified. Administrative privledges: ${isAdministrator]`
            }
+ Response 403 (application/json)
    + Body
    
            {
                "message": "You do not administrative privileges on this api"
            }

### Delete a user [DELETE]

+ Request (application/json)

    + Body
    
            {
                "name": "User's name"
            }

+ Response 201 (application/json)

    + Headers

            Location: /users/${id}

    + Body

            {
                "message": `User ${name} deleted.`
            }
+ Response 403 (application/json)
    + Body
    
            {
                "message": "You do not administrative privileges on this api"
                }